export enum ErrorCode {
    UNAUTHORIZED = "UNAUTHORIZED",
    USER_EMAIL_DUPLICATE = "USER_EMAIL_DUPLICATE",
    STARTUP_WITH_ID_DOES_NOT_EXISTS = "STARTUP_WITH_ID_DOES_NOT_EXISTS",
    FUNDING_ROUND_OVERLAP = "FUNDING_ROUND_OVERLAP",
}