export enum ErrorCode {
    UNAUTHORIZED = "UNAUTHORIZED",
    USER_EMAIL_DUPLICATE = "USER_EMAIL_DUPLICATE",
    STARTUP_WITH_ID_DOES_NOT_EXISTS = "STARTUP_WITH_ID_DOES_NOT_EXISTS",
    FUNDING_ROUND_OVERLAP = "FUNDING_ROUND_OVERLAP",
    INVESTOR_WITH_ID_DOES_NOT_EXISTS = "INVESTOR_WITH_ID_DOES_NOT_EXISTS",
    CANNOT_UPDATE_EXITED_STARTUP = "CANNOT_UPDATE_EXITED_STARTUP",
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
    CANNOT_CREATE_FUNDING_ROUND_FOR_EXITED_STARTUP = "CANNOT_CREATE_FUNDING_ROUND_FOR_EXITED_STARTUP",
    FUNDING_ROUND_END_CANNOT_BE_LOWER_THAN_START = "FUNDING_ROUND_END_CANNOT_BE_LOWER_THAN_START",
}