export enum NotificationTypes {
    MESSAGE = 'MESSAGE',
    INVESTMENT = 'INVESTMENT',
    FUNDING_ROUND_DEADLINE = 'FUNDING_ROUND_DEADLINE',
    FUNDING_ROUND_CHANGE_PROPOSAL = 'FUNDING_ROUND_CHANGE_PROPOSAL',
    FUNDING_ROUND_CHANGE_PROPOSAL_FINISHED = 'FUNDING_ROUND_CHANGE_PROPOSAL_FINISHED',
    FUNDING_ROUND_ENDED = 'FUNDING_ROUND_ENDED'
}